# $ docker-compose up
# $ docker-compose down
version: '3'

services:
  # Database
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      

  # Word-press
  wordpress:
    image: wordpress
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '4040:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: wordpress
